language: node_js
node_js:
  - "7"
  - "8"
  - "node"
deploy:
  provider: npm
  email: antoine@subforce-solutions.com
  on:
    tags: true
    repo: ajouve/html2docx
  api_key:
    secure: VLpdBnPSBrVYcoHAqtfavClfVbvfmK6qQvD5AatumzR3060eZ+AwklxZt/HM1MCfyBzAhH77UWDWglcrvFnqwRDrB8vnAP4Nb2x6LcCo+Ui+oda7i0oBfdDbLsRYsXT8hAQ1Nh8URDn/E6DxlTQaWuR2rsvGEbVS0hm/EHGsJX5Z9pPzQeGOkVqPGCsTZu+onboRaMkZxPjA/z16fdaF1sKaoU3J0Tye68SttOFVxNN7VsklDDTTya33+TzVT+sZYlyem2CGZRPqG+ZCjOhDjVusNlMek4j1xityAgR5q+5dBpkEU8B2zlJZQ0FPGKkpELdKgRdGwASItubfit1W/gjo0e/Nuo9Zr+FZ8PMuQnPxHjJEQcAdf8KjYIWdLB1/dBQYuJMJP55ghyGL2PjNJPLDSEGv6VvuYk+jNfy7mMsmmiWooSp3NVhcMk5y0v9RVQfzshseBcxmof4trtCszxEDE/10lsswvY2J55ixYab/tlzfHrSt0RDX/Z81cxrh1iZqoME56JlMKdSsMmkIGmCwD1S68W+ZmbxvUWXlxV6nXF/bWzyIFy1xEwlay/Dcipi+UPIE6iIlnKf+pWS9OxrHE9XFcAE1pJLfwFwkMPckTuAtRhnFWZ+AHMjq4qKIHp+tymevTYrfW5NhRdPD2y2DpCtZ//p2ahUeUZbyLAc=
